event_type: temp_humidity.v2

fields:

  device_id:
    type: string
    required: true

  event_time_utc:
    type: string
    required: true
    description: "UTC timestamp emitted by device"

  temperature_f:
    type: float
    required: true

  humidity_pct:
    type: float
    required: true

  sensor:
    type: string
    required: true

  serial_number:
    type: string
    required: true

  battery_pct:
    type: float
    required: false
    min: 0
    max: 100

  firmware_version:
    type: string
    required: false