fields:
  - name: device_id
    type: string
    nullable: false

  - name: event_time_utc
    type: string
    nullable: false

  - name: temperature_f
    type: double
    nullable: true

  - name: humidity_pct
    type: double
    nullable: true

  - name: battery_pct
    type: double
    nullable: true

  - name: firmware_version
    type: string
    nullable: true